/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bselmux_9 (
    input [3:0] sel,
    input [15:0] rdata,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (sel)
      4'h0: begin
        out = rdata;
      end
      4'h1: begin
        out = 16'h0001;
      end
      4'h2: begin
        out = 16'h0002;
      end
      4'h3: begin
        out = 16'h0003;
      end
      4'h4: begin
        out = 16'h0004;
      end
      4'h5: begin
        out = 16'h0005;
      end
      4'h6: begin
        out = 16'h0006;
      end
      4'h7: begin
        out = 16'h0007;
      end
      4'h8: begin
        out = 16'h0008;
      end
      4'h9: begin
        out = 16'h0080;
      end
      4'ha: begin
        out = 16'h0000;
      end
      4'hb: begin
        out = 16'h003c;
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
