/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module orientation_unit_11 (
    input [3:0] button,
    input [1:0] orientation_state,
    output reg [3:0] up_display,
    output reg [3:0] direction
  );
  
  
  
  always @* begin
    direction = 4'h0;
    up_display = 4'h0;
    
    case (orientation_state)
      2'h0: begin
        up_display = 4'h1;
      end
      2'h1: begin
        up_display = 4'h8;
      end
      2'h2: begin
        up_display = 4'h2;
      end
      2'h3: begin
        up_display = 4'h4;
      end
    endcase
    
    case (orientation_state)
      2'h0: begin
        
        case (button)
          4'h1: begin
            direction = 4'h1;
          end
          4'h2: begin
            direction = 4'h2;
          end
          4'h4: begin
            direction = 4'h4;
          end
          4'h8: begin
            direction = 4'h8;
          end
        endcase
      end
      2'h1: begin
        
        case (button)
          4'h1: begin
            direction = 4'h4;
          end
          4'h2: begin
            direction = 4'h8;
          end
          4'h4: begin
            direction = 4'h2;
          end
          4'h8: begin
            direction = 4'h1;
          end
        endcase
      end
      2'h2: begin
        
        case (button)
          4'h1: begin
            direction = 4'h2;
          end
          4'h2: begin
            direction = 4'h1;
          end
          4'h4: begin
            direction = 4'h8;
          end
          4'h8: begin
            direction = 4'h4;
          end
        endcase
      end
      2'h3: begin
        
        case (button)
          4'h1: begin
            direction = 4'h8;
          end
          4'h2: begin
            direction = 4'h4;
          end
          4'h4: begin
            direction = 4'h1;
          end
          4'h8: begin
            direction = 4'h2;
          end
        endcase
      end
    endcase
  end
endmodule
