/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wdselmux_7 (
    input [1:0] wdsel,
    input [15:0] alu,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (wdsel)
      2'h0: begin
        out = alu;
      end
      2'h1: begin
        out = 16'hffff;
      end
      2'h2: begin
        out = 16'h000f;
      end
      2'h3: begin
        out = 16'h0000;
      end
      default: begin
        out = alu;
      end
    endcase
  end
endmodule
